---
title: "COVID-19 daily data download"
author: "Cameron Patrick"
date: "9 October 2021"
output: 
  html_document:
    toc: true
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = TRUE,
  message = TRUE,
  comment = NA
)
```

## Load R packages

```{r packages, warning = FALSE, message = FALSE}
library(tidyverse)
library(lubridate)
library(glue)
library(here)
library(gt)
```

## Check output file

```{r}
rds_file <- here("data", "cases", 
                 glue("covid19_aus_munged_{Sys.Date()}.Rds"))
cat("Daily output file:", rds_file, "\n")
```

## Data download

Aus data from: <https://github.com/pappubahry/AU_COVID19>

Note NZ file has date in URL! Totals based on notification date don't seem to line up with announcements which are ~ 1pm to 1pm kiwi time. See <https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-case-demographics>

```{r data-download, warning = FALSE, message = FALSE}
nz_url_date <- "2021-10-13"
#nz_url_date <- Sys.Date()

covid19_vic <- read_csv("https://github.com/pappubahry/AU_COVID19/raw/master/time_series_vic_sources.csv")
covid19_nsw <- read_csv("https://github.com/pappubahry/AU_COVID19/raw/master/time_series_nsw_sources.csv")
covid19_act <- read_csv("https://github.com/pappubahry/AU_COVID19/raw/master/time_series_act_sources.csv")
covid19_nz <- read_csv(glue("https://www.health.govt.nz/system/files/documents/pages/covid_cases_{nz_url_date}.csv"))
```

## Data wrangling

```{r}
extra_info <- tribble(
  ~state, ~date, ~daily_confirmed,
  "VIC", "2021-10-01", 1488,
  "VIC", "2021-10-02", 1220,
  "VIC", "2021-10-03", 1377,
  "VIC", "2021-10-04", 1763,
  "VIC", "2021-10-05", 1420,
  "VIC", "2021-10-06", 1638,
  "VIC", "2021-10-07", 1838,
  "VIC", "2021-10-08", 1965,
  "VIC", "2021-10-09", 1890,
  "VIC", "2021-10-10", 1612,
  "VIC", "2021-10-11", 1466,
  "VIC", "2021-10-12", 1571,
  "VIC", "2021-10-13", 2297,
  
  "NSW", "2021-10-01", 813,
  "NSW", "2021-10-02", 667,
  "NSW", "2021-10-03", 623,
  "NSW", "2021-10-04", 608,
  "NSW", "2021-10-05", 594,
  "NSW", "2021-10-06", 587,
  "NSW", "2021-10-07", 646,
  "NSW", "2021-10-08", 580,
  "NSW", "2021-10-09", 477,
  "NSW", "2021-10-10", 496,
  "NSW", "2021-10-11", 360,
  "NSW", "2021-10-12", 444,
  "NSW", "2021-10-13", 406,
  
  "ACT", "2021-10-01", 52,
  "ACT", "2021-10-02", 38,
  "ACT", "2021-10-03", 28,
  "ACT", "2021-10-04", 33,
  "ACT", "2021-10-05", 28,
  "ACT", "2021-10-06", 41,
  "ACT", "2021-10-07", 40,
  "ACT", "2021-10-08", 25,
  "ACT", "2021-10-09", 30,
  "ACT", "2021-10-10", 32,
  "ACT", "2021-10-11", 28,
  "ACT", "2021-10-12", 51,
) %>%
  mutate(date = ymd(date))
```

```{r}
outbreak_dates <- tribble(
  ~state, ~outbreak_date,
  "VIC", "2021-07-12",
  "NSW", "2021-06-15",
  "ACT", "2021-08-12",
  "NZ", "2021-08-17",
) %>%
  mutate(outbreak_date = ymd(outbreak_date))
```


```{r data-munge}
selected_states_abbrev <- c("VIC", "NSW", "ACT", "NZ")
selected_states_full <- c("Victoria", "New South Wales", "Australian Capital Territory", "New Zealand")

covid19_aus_munged <- bind_rows(
  "VIC" = covid19_vic %>%
    transmute(date,
              daily_confirmed = local_contact + local_unknown + under_investigation),
  "NSW" = covid19_nsw %>%
    transmute(date = date - 1,
              daily_confirmed = interstate + local_contact + local_unknown + under_investigation),
  "ACT" = covid19_act %>%
    transmute(date,
              daily_confirmed = interstate + local_contact + local_unknown + under_investigation),
  "NZ" = covid19_nz %>%
    filter(`Overseas travel` != "Yes" & `Report Date` < ymd(str_extract(nz_url_date, "^[0-9-]+"))) %>%
    group_by(date = `Report Date`) %>%
    summarise(daily_confirmed = n()),
  .id = "state"
) %>%
  bind_rows(anti_join(extra_info, ., by = c("state", "date"))) %>%
  left_join(outbreak_dates, by = "state") %>%
  group_by(state) %>%
  complete(date = seq(min(date), max(date), by = "day"),
           fill = list(daily_confirmed = 0)) %>%
  ungroup() %>%
  mutate(state = factor(state, levels = selected_states_abbrev),
         state_full = factor(state, levels = selected_states_abbrev, labels = selected_states_full))
```

## Most recent case numbers

```{r}
covid19_aus_munged %>%
  arrange(state, desc(date)) %>%
  group_by(state) %>%
  summarise(head(cur_data(), n = 5)) %>%
  select(state, date, daily_confirmed) %>%
  gt()
```


## Save as R data file

```{r}
saveRDS(covid19_aus_munged, rds_file)
```

## R session info

```{r session-info}
Sys.time()
sessionInfo()
```

