---
title: "Victoria 2021 Covid outbreak by LGA"
author: "Cameron Patrick"
date: "`r strftime(Sys.Date(), '%e %B %Y')`"
output: 
  html_document:
    toc: true
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  comment = NA,
  fig.width = 9,
  fig.height = 6,
  dpi = 130,
  fig.retina = 2,
  dev = "ragg_png"
)
```

```{r packages}
library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)
library(here)
library(glue)
library(gt)
library(mgcv)
library(broom)
library(geofacet)
```

```{r}
theme_set(
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        legend.position = "off",
        plot.title = element_text(size = rel(1.0)),
        plot.caption = element_text(size = rel(7/11)),
        strip.background = element_blank(),
        strip.text = element_text(hjust = 0, size = rel(7/11)),
        axis.text = element_text(colour = "black", size = rel(7/11)),
        axis.title = element_text(size = rel(1)))
)
```

```{r}
plot_start_date <- "2021-09-01"
```

```{r}
plot_file <- function(base) {
  here("output", "plots", Sys.Date(), base)
}
```

## Data import

Note, data obtained from:
<https://www.coronavirus.vic.gov.au/victorian-coronavirus-covid-19-data>,
<https://www.dhhs.vic.gov.au/ncov-covid-cases-by-lga-source-csv>

Vaccination data from: <https://www.health.gov.au/resources/collections/covid-19-vaccination-geographic-vaccination-rates-lga>

LGA population data from: <https://www.planning.vic.gov.au/land-use-and-population-research/victoria-in-future>

```{r}
cases_file_date <- ymd("2021-10-11")
#cases_file_date <- Sys.Date()

cases_file_name <- glue("NCOV_COVID_Cases_by_LGA_Source_{strftime(cases_file_date, '%Y%m%d')}.csv")
cases_file_path <- here("data", "cases_LGA", cases_file_name)
cases_file_url <- glue("https://www.dhhs.vic.gov.au/sites/default/files/documents/{strftime(cases_file_date, '%Y%m')}/{cases_file_name}")
if (fs::file_exists(cases_file_path)) {
  cat("Latest case file", cases_file_name, "exists.\n")
} else {
  curl::curl_download(cases_file_url, cases_file_path, quiet = TRUE)
}
```

```{r}
fix_lga <- function(lga_full) {
  str_replace_all(lga_full, r"( \([A-Za-z.]+\))", "")
}
```


```{r load-data}
data_file <- last(sort(Sys.glob(here("data", "cases_LGA", "NCOV_COVID_Cases_by_LGA_Source_*.csv"))))
cat("Latest data file:", data_file, "\n")
vic_lga_orig <- read_csv(data_file)
```


```{r}
nsw_lga_orig <- read_csv("https://data.nsw.gov.au/data/dataset/97ea2424-abaf-4f3e-a9f2-b5c883f42b6a/resource/2776dbb8-f807-4fb2-b1ed-184a6fc2c8aa/download/confirmed_cases_table4_location_likely_source.csv")
write_csv(nsw_lga_orig, here("data", "cases_LGA", glue("nsw_lga_{strftime(max(nsw_lga_orig$notification_date), '%Y%m%d')}.csv")))
```


```{r}
melb_grid <- read_csv(here("data", "LGA", "melb_LGA_grid.csv"))
lga_regions <- read_csv(here("data", "LGA", "LGA_regions.csv")) %>%
  select(lga = LGA, region = Region) %>%
  mutate(lga = str_to_title(lga))
regional_grid <- read_csv(here("data", "LGA", "regional_grid.csv"))

syd_grid <- read_csv(here("data", "LGA", "syd_LGA_grid.csv"))
```

```{r}
lga_pop_data_orig <- read_xlsx(here("data", "LGA", "VIF2019_Population_Service_Ages_LGA_2036.xlsx"), sheet = "Age Sex", skip = 11)
lga_pop_data <- lga_pop_data_orig %>%
  clean_names() %>%
  remove_empty() %>%
  select(lga_full = lga, lga_population_2021 = persons_total_40) %>%
  mutate(lga = fix_lga(lga_full))
```

```{r}
nsw_lga_pop_data_orig <- read_xlsx(here("data", "LGA", "2019 NSW Population Projections ASGS 2019 LGA.xlsx"), sheet = "LGA population projections", skip = 5)
nsw_lga_pop_data <- nsw_lga_pop_data_orig %>%
  clean_names() %>%
  select(lga_full = asgs_2019_lga, lga_population_2021 = x2021) %>%
  filter(lga_full != "NSW Total", !is.na(lga_population_2021)) %>%
  mutate(lga = fix_lga(lga_full))
```

```{r}
vic_lga <- vic_lga_orig %>%
  filter(acquired != "Travel overseas") %>%
  group_by(lga_full = Localgovernmentarea, date = diagnosis_date) %>%
  summarise(confirmed = n()) %>%
  ungroup() %>%
  complete(lga_full, date, fill = list(confirmed = 0)) %>%
  mutate(lga = fix_lga(lga_full)) %>%
  left_join(select(lga_pop_data, lga, lga_population_2021)) %>%
  mutate(confirmed_per_100k = confirmed / lga_population_2021 * 100000)
```

```{r}
nsw_lga <- nsw_lga_orig %>%
  filter(likely_source_of_infection != "Overseas") %>%
  group_by(lga_full = lga_name19, date = notification_date) %>%
  summarise(confirmed = n()) %>%
  ungroup() %>%
  complete(lga_full, date, fill = list(confirmed = 0)) %>%
  mutate(lga = fix_lga(lga_full)) %>%
  left_join(select(nsw_lga_pop_data, lga, lga_population_2021)) %>%
  mutate(confirmed_per_100k = confirmed / lga_population_2021 * 100000)
```

```{r}
fs::dir_create(here("output", "plots", Sys.Date()))
```


## Metro Melb



```{r}
melb_lga <- vic_lga %>%
  filter(date >= "2021-09-01") %>%
  filter(lga %in% melb_grid$name)
stopifnot(length(unique(melb_lga$lga)) == nrow(filter(melb_grid, !str_detect(name, "^ocean"))))
```

```{r}
melb_overall <- melb_lga %>%
  group_by(date) %>%
  summarise(confirmed = sum(confirmed),
            lga_population_2021 = sum(lga_population_2021),
            confirmed_per_100k = confirmed / lga_population_2021 * 100000) %>%
  ungroup() %>%
  expand_grid(lga = melb_grid$name)
```


```{r}
label_dat <- melb_lga %>%
  summarise(date = min(date),
            confirmed = max(confirmed),
            confirmed_per_100k = max(confirmed_per_100k)) %>%
  expand_grid(lga = melb_grid$name) %>%
  mutate(is_ocean = str_detect(lga, "^ocean"),
         label = lga %>%
           str_replace("^Greater ", "Gtr. ") %>%
           str_replace("Mornington Peninsula", "Morn. Pen.") %>%
           str_replace("^ocean.*", ""))
```


```{r}
melb_lga %>%
  ggplot(aes(x = date, y = confirmed)) +
  geom_smooth(method = "gam", se = FALSE, colour = "chartreuse3", alpha = 0.3) +
  geom_point(colour = "chartreuse4", pch = 1, size = 0.5, stroke = 0.5, alpha = 1) +
  geom_text(data = label_dat, aes(label = label),
            hjust = 0, vjust = 1,
            size = 7 / .pt) +
  geom_rect(data = filter(label_dat, is_ocean),
            fill = "lightskyblue", 
            xmin = -Inf, xmax = Inf,
            ymin = -Inf, ymax = Inf) +
  facet_geo(vars(lga), grid = melb_grid) +
  scale_x_date(date_labels = "%e %b", date_breaks = "2 weeks") +
  #scale_x_date(date_labels = "%e %b", breaks = ymd(c("2021-09-01", "2021-09-15", "2021-10-01"))) +
  expand_limits(x = ymd("2021-10-02")) +
  theme(strip.text = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "grey60"),
        panel.spacing = unit(2, "pt")) +
  labs(x = NULL, 
       y = "Daily confirmed cases excluding overseas",
       caption = glue("Plot created {Sys.Date()}; most recent cases {max(melb_lga$date)}. Data: Vic DHHS. Code: github.com/cmrnp/armchair-covid"))
ggsave(plot_file("cases_melb_lga.png"),
       width = 9, height = 6, dpi = 400, dev = ragg::agg_png)
```

```{r}
melb_lga %>%
  ggplot(aes(x = date, y = confirmed_per_100k)) +
  geom_smooth(method = "gam", se = FALSE, colour = "grey80", alpha = 0.3, data = melb_overall) +
  geom_smooth(method = "gam", se = FALSE, colour = "chartreuse3", alpha = 0.3) +
  geom_point(colour = "chartreuse4", pch = 1, size = 0.5, stroke = 0.5, alpha = 1) +
  geom_text(data = label_dat, aes(label = label),
            hjust = 0, vjust = 1,
            size = 7 / .pt) +
  geom_rect(data = filter(label_dat, is_ocean),
            fill = "lightskyblue", 
            xmin = -Inf, xmax = Inf,
            ymin = -Inf, ymax = Inf) +
  facet_geo(vars(lga), grid = melb_grid) +
  scale_x_date(date_labels = "%e %b", date_breaks = "2 weeks") +
  #scale_x_date(date_labels = "%e %b", breaks = ymd(c("2021-09-01", "2021-09-15", "2021-10-01"))) +
  expand_limits(x = ymd("2021-10-02")) +
  theme(strip.text = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "grey60"),
        panel.spacing = unit(2, "pt")) +
  labs(x = NULL, 
       y = "Daily confirmed cases excluding overseas, per 100k population",
       caption = glue("Grey curves show metro average. Plot created {Sys.Date()}; most recent cases {max(melb_lga$date)}. Data: Vic DHHS. Code: github.com/cmrnp/armchair-covid"))
ggsave(plot_file("cases_melb_lga_pop.png"),
       width = 9, height = 6, dpi = 400, dev = ragg::agg_png)
```


## Regional Vic

```{r}
regional_lga <- vic_lga %>%
  inner_join(lga_regions) %>%
  mutate(region = str_replace(region, "Inner Melbourne|Outer Metropolitan|Metropolitan Melbourne", "Melbourne")) %>%
  group_by(region, date) %>%
  summarise(confirmed = sum(confirmed),
            region_population = sum(lga_population_2021),
            confirmed_per_100k = confirmed / region_population * 100000) %>%
  ungroup()
stopifnot(length(unique(regional_lga$region)) == nrow(regional_grid))
```

```{r}
label_dat <- regional_lga %>%
  summarise(date = ymd("2021-09-01"),
         confirmed = max(confirmed),
         confirmed_per_100k = max(confirmed_per_100k)) %>%
  expand_grid(region = regional_grid$name) %>%
  mutate(is_ocean = FALSE,
         label = region)
regional_lga %>%
  filter(date >= "2021-09-01") %>%
  ggplot(aes(x = date, y = confirmed_per_100k)) +
  geom_smooth(method = "gam", se = FALSE, colour = "chartreuse3", alpha = 0.3) +
  geom_point(colour = "chartreuse4", pch = 1, size = 0.5, stroke = 0.5, alpha = 1) +
  geom_text(data = label_dat, aes(label = label),
            hjust = 0, vjust = 1,
            size = 7 / .pt) +
  geom_rect(data = filter(label_dat, is_ocean),
            fill = "lightskyblue", 
            xmin = -Inf, xmax = Inf,
            ymin = -Inf, ymax = Inf) +
  facet_geo(vars(region), grid = regional_grid) +
  scale_x_date(date_labels = "%e %b", date_breaks = "2 weeks") +
  #scale_x_date(date_labels = "%e %b", breaks = ymd(c("2021-09-01", "2021-09-15", "2021-10-01"))) +
  expand_limits(x = ymd("2021-10-02")) +
  theme(strip.text = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "grey60"),
        panel.spacing = unit(2, "pt")) +
  labs(x = NULL, 
       y = "Daily confirmed cases excluding overseas, per 100k population",
       caption = glue("Plot created {Sys.Date()}; most recent cases {max(vic_lga$date)}. Data: Vic DHHS. Code: github.com/cmrnp/armchair-covid"))
ggsave(plot_file("cases_regional_vic_pop.png"),
       width = 9, height = 6, dpi = 400, dev = ragg::agg_png)
```

## Vaccination

Now using data from <https://vaccinedata.covid19nearme.com.au/data/geo/air_lga.csv>

```{r}
vax_data_orig <- read_csv(here("data", "vax_LGA", "air_lga.csv"))
```

```{r}
vax_data <- vax_data_orig %>%
  clean_names() %>%
  select(state,
         date = date_as_at,
         lga_full = abs_name,
         dose_1 = air_first_dose_pct,
         dose_2 = air_second_dose_pct) %>%
  pivot_longer(dose_1:dose_2, names_to = "dose", values_to = "prop") %>%
  mutate(prop = prop / 100) %>%
  mutate(prop = if_else(prop >= 0.9499, 0.951, prop))
```


```{r}
vax_vic <- vax_data %>% 
  filter(state == "VIC") %>%
  mutate(lga = fix_lga(lga_full))
vax_melb <- vax_vic %>%
  filter(lga %in% melb_grid$name)
```

```{r}
label_dat <- vax_melb %>%
  summarise(date = min(date),
            prop = 1,
            dose = "dose_1") %>%
  expand_grid(lga = melb_grid$name) %>%
  mutate(is_ocean = str_detect(lga, "^ocean"),
         label = lga %>%
           str_replace("^Greater ", "Gtr. ") %>%
           str_replace("Mornington Peninsula", "Morn. Pen.") %>%
           str_replace("^ocean.*", ""))
vax_melb %>%
  #filter(date >= "2021-09-01") %>%
  ggplot(aes(x = date, y = prop, colour = dose, group = dose)) +
  # geom_hline(yintercept = 0.7, size = 0.5, colour = "grey80") +
  # geom_hline(yintercept = 0.8, size = 0.5, colour = "grey80") +
  # geom_hline(yintercept = 0.9, size = 0.5, colour = "grey80") +
  geom_rect(data = filter(label_dat, !is_ocean),
            fill = "chartreuse3", colour = NA,
            alpha = 0.15,
            xmin = -Inf, xmax = Inf,
            ymin = 0.7, ymax = Inf,
            show.legend = FALSE) +
  geom_rect(data = filter(label_dat, !is_ocean),
            fill = "chartreuse3", colour = NA,
            alpha = 0.2,
            xmin = -Inf, xmax = Inf,
            ymin = 0.8, ymax = Inf,
            show.legend = FALSE) +
  geom_rect(data = filter(label_dat, !is_ocean),
            fill = "chartreuse3", colour = NA,
            alpha = 0.25,
            xmin = -Inf, xmax = Inf,
            ymin = 0.9, ymax = Inf,
            show.legend = FALSE) +
  geom_line(alpha = 1, size = 0.75) +
  geom_point(size = 0.75, stroke = 0.75, alpha = 1) +
  geom_text(data = label_dat, aes(label = label),
            hjust = 0, vjust = 1,
            size = 7 / .pt,
            colour = "black",
            show.legend = FALSE) +
  geom_rect(data = filter(label_dat, is_ocean),
            fill = "lightskyblue", 
            xmin = -Inf, xmax = Inf,
            ymin = -Inf, ymax = Inf,
            show.legend = FALSE) +
  facet_geo(vars(lga), grid = melb_grid) +
  scale_y_continuous(limits = c(0,1),
                     breaks = seq(0, 1, by = 0.2),
                     labels = scales::label_percent(accuracy = 1)) +
  scale_x_date(date_labels = "%e %b", date_breaks = "2 weeks") +
  #scale_x_date(date_labels = "%e %b", breaks = ymd(c("2021-09-01", "2021-09-15", "2021-10-01"))) +
  #expand_limits(x = ymd("2021-10-02")) +
  scale_colour_manual(NULL,
                      breaks = c("dose_1", "dose_2"),
                      labels = c("First dose", "Second dose"),
                      values = c("firebrick2", "firebrick4")) +
  theme(strip.text = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "grey60"),
        panel.spacing = unit(2, "pt"),
        panel.grid = element_blank(),
        legend.position = c(1, 0),
        legend.justification = c(1, 0),
        legend.margin = margin(0, 0, 0, 0)) +
  labs(x = NULL, 
       y = "Percentage of LGA population vaccinated",
       caption = glue("Plot created {Sys.Date()}; most recent data {max(vax_melb$date)}. Data: Australian Dept of Health. Code: github.com/cmrnp/armchair-covid"))
ggsave(plot_file("vax_melb_lga.png"),
       width = 9, height = 6, dpi = 400, dev = ragg::agg_png)

```

## Metro Melb, coloured by vax %

```{r}
vax_latest_lga <- vax_vic %>%
  filter(date == max(date), dose == "dose_1") %>%
  select(lga, vax_prop = prop)
```

```{r}
label_dat <- melb_lga %>%
  summarise(date = min(date),
            confirmed = max(confirmed),
            confirmed_per_100k = max(confirmed_per_100k)) %>%
  expand_grid(lga = melb_grid$name) %>%
  left_join(vax_latest_lga) %>%
  mutate(is_ocean = str_detect(lga, "^ocean"),
#         label = glue("{lga}\n({round(100*vax_prop)}% vax.)") %>%
         label = lga %>%
           str_replace("^Greater ", "Gtr. ") %>%
           str_replace("Mornington Peninsula", "Morn. Pen.") %>%
           str_replace("^ocean.*", ""))
```

```{r}
vax_cols <- RColorBrewer::brewer.pal(6, "RdYlGn")
vax_cols_dark <- colorspace::darken(vax_cols, 0.2)
melb_lga %>%
  left_join(vax_latest_lga) %>%
  ggplot(aes(x = date, y = confirmed_per_100k, colour = vax_prop)) +
  stat_smooth(method = "gam", se = FALSE, colour = "grey60", data = melb_overall, geom = "line", size = 2, alpha = 0.4) +
  stat_smooth(method = "gam", se = FALSE, geom = "line",
              size = 2, alpha = 0.4) +
  geom_point(pch = 1, size = 0.5, stroke = 0.5, alpha = 1) +
  geom_text(data = label_dat, aes(label = label),
            hjust = 0, vjust = 1,
            size = 7 / .pt,
            colour = "black") +
  geom_rect(data = filter(label_dat, is_ocean),
            fill = "lightskyblue", 
            xmin = -Inf, xmax = Inf,
            ymin = -Inf, ymax = Inf) +
  facet_geo(vars(lga), grid = melb_grid) +
  scale_x_date(date_labels = "%e %b", date_breaks = "2 weeks") +
  scale_colour_stepsn(breaks = seq(0.65, 0.95, by = 0.05),
                      limits = c(0.65, 0.95),
                      labels = scales::label_percent(accuracy = 1),
                      colours = vax_cols_dark,
                      guide = guide_coloursteps(show.limits = TRUE, direction = "horizontal", title.position = "top", barwidth = unit(144, "pt"), barheight = unit(11, "pt"))) +
  #scale_x_date(date_labels = "%e %b", breaks = ymd(c("2021-09-01", "2021-09-15", "2021-10-01"))) +
  expand_limits(x = ymd("2021-10-02")) +
  theme(strip.text = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "grey60"),
        panel.spacing = unit(2, "pt"),
        legend.position = c(1, 0),
        legend.justification = c(1, 0),
        legend.text = element_text(size = rel(7/11)),
        legend.title = element_text(size = rel(7/11)),
        legend.margin = margin(0, 5.5, 0, 5.5, "pt")) +
  labs(colour = "% vaccinated (single dose)",
       x = NULL, 
       y = "Daily confirmed cases excluding overseas, per 100k population",
       caption = glue("Grey curves show metro average. Plot created {Sys.Date()}; most recent cases {max(melb_lga$date)}. Data: Vic DHHS. Code: github.com/cmrnp/armchair-covid"))
ggsave(plot_file("cases_melb_lga_pop_vax.png"),
       width = 9, height = 6, dpi = 400, dev = ragg::agg_png)
```


```{r}
vax_shading_dat <- vax_vic %>%
  filter(dose == "dose_1", lga %in% melb_grid$name) %>%
  select(lga, date, vax_prop = prop) %>%
  arrange(lga, date) %>%
  group_by(lga) %>%
  mutate(date = pmax(date, min(melb_lga$date) - 2),
         date_end = lead(date, default = max(melb_lga$date) + 2)) %>%
  ungroup()
```

```{r}
vax_cols <- RColorBrewer::brewer.pal(9, "RdYlGn")
vax_cols_light <- colorspace::lighten(vax_cols, 0.7)
melb_lga %>%
  ggplot(aes(x = date, y = confirmed_per_100k)) +
  geom_rect(data = vax_shading_dat,
            aes(fill = vax_prop,
                xmin = date,
                xmax = date_end),
            ymin = -Inf, ymax = Inf,
            alpha = 1,
            inherit.aes = FALSE) +
  stat_smooth(method = "gam", se = FALSE, geom = "line",
              size = 3, alpha = 0.8, colour = "white") +
  stat_smooth(method = "gam", se = FALSE, colour = "grey60",
              data = melb_overall, geom = "line", size = 1.5, alpha = 0.4) +
  geom_point(pch = 1, size = 0.5, stroke = 0.5, alpha = 1) +
  geom_text(data = label_dat, aes(label = label),
            hjust = 0, vjust = 1,
            size = 7 / .pt,
            colour = "black") +
  geom_rect(data = filter(label_dat, is_ocean),
            fill = "lightskyblue", 
            xmin = -Inf, xmax = Inf,
            ymin = -Inf, ymax = Inf) +
  facet_geo(vars(lga), grid = melb_grid) +
  scale_x_date(date_labels = "%e %b",
               breaks = ymd(c("2021-09-01", "2021-09-15", "2021-10-01")),
               limits = c(min(melb_lga$date) - 2, max(melb_lga$date) + 2),
               expand = expansion(0)) +
  scale_fill_stepsn(#breaks = seq(0.4, 0.95, by = 0.05),
    breaks = c(0.4, 0.5, 0.6, seq(0.7, 1, by = 0.05)),
    limits = c(0.4, 1),
    #labels = scales::label_percent(accuracy = 1),
    labels = c("40%", "50%", "60%", "70%", "", "80%", "", "90%", "", "100%"),
    colours = vax_cols_light,
    guide = guide_coloursteps(#show.limits = TRUE,
                              even.steps = FALSE,
                              direction = "horizontal",
                              title.position = "top",
                              barwidth = unit(144, "pt"),
                              barheight = unit(11, "pt"))) +
  theme(strip.text = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "grey60"),
        panel.spacing = unit(2, "pt"),
        panel.grid = element_blank(),
        legend.position = c(1, 0),
        legend.justification = c(1, 0),
        legend.text = element_text(size = rel(7/11)),
        legend.title = element_text(size = rel(7/11)),
        legend.margin = margin(0, 5.5, 0, 5.5, "pt")) +
  labs(fill = "% vaccinated (single dose)",
       x = NULL, 
       y = "Daily confirmed cases excluding overseas, per 100k population",
       caption = glue("Grey curves show metro average. Plot created {Sys.Date()}; most recent cases {max(melb_lga$date)}. Data: Vic DHHS. Code: github.com/cmrnp/armchair-covid"))
ggsave(plot_file("cases_melb_lga_pop_vax_2.png"),
       width = 9, height = 6, dpi = 400, dev = ragg::agg_png)
```

## Metro Sydney

```{r}
syd_lga <- nsw_lga %>%
  filter(date >= "2021-08-01") %>%
  filter(lga %in% syd_grid$name)
stopifnot(length(unique(syd_lga$lga)) == nrow(filter(syd_grid, !str_detect(name, "^ocean"))))
```

```{r}
syd_overall <- syd_lga %>%
  group_by(date) %>%
  summarise(confirmed = sum(confirmed),
            lga_population_2021 = sum(lga_population_2021),
            confirmed_per_100k = confirmed / lga_population_2021 * 100000) %>%
  ungroup() %>%
  expand_grid(lga = syd_grid$name)
```


```{r}
label_dat <- syd_lga %>%
  summarise(date = min(date),
            confirmed = max(confirmed),
            confirmed_per_100k = max(confirmed_per_100k)) %>%
  expand_grid(lga = syd_grid$name) %>%
  mutate(is_ocean = str_detect(lga, "^ocean"),
         label = lga %>%
           str_replace("^Greater ", "Gtr. ") %>%
           str_replace("Mornington Peninsula", "Morn. Pen.") %>%
           str_replace("Canterbury-Bankstown", "C'bury-B'town") %>%
           str_replace("^ocean.*", ""))
```


```{r}
syd_lga %>%
  ggplot(aes(x = date, y = confirmed_per_100k)) +
  geom_smooth(method = "gam", se = FALSE, colour = "grey80", alpha = 0.3, data = syd_overall) +
  geom_smooth(method = "gam", se = FALSE, colour = "chartreuse3", alpha = 0.3) +
  geom_point(colour = "chartreuse4", pch = 1, size = 0.5, stroke = 0.5, alpha = 1) +
  geom_text(data = label_dat, aes(label = label),
            hjust = 0, vjust = 1,
            size = 7 / .pt) +
  geom_rect(data = filter(label_dat, is_ocean),
            fill = "lightskyblue", 
            xmin = -Inf, xmax = Inf,
            ymin = -Inf, ymax = Inf) +
  facet_geo(vars(lga), grid = syd_grid) +
  scale_x_date(date_labels = "%b", date_breaks = "1 month") +
  #scale_x_date(date_labels = "%e %b", breaks = ymd(c("2021-09-01", "2021-09-15", "2021-10-01"))) +
  #expand_limits(x = ymd("2021-10-02")) +
  theme(strip.text = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "grey60"),
        panel.spacing = unit(2, "pt")) +
  labs(x = NULL, 
       y = "Daily confirmed cases excluding overseas, per 100k population",
       caption = glue("Grey curves show metro average. Plot created {Sys.Date()}; most recent cases {max(syd_lga$date)}. Data: NSW Health. Code: github.com/cmrnp/armchair-covid"))
ggsave(plot_file("cases_syd_lga_pop.png"),
       width = 9, height = 6, dpi = 400, dev = ragg::agg_png)
```

## R session info

```{r session-info}
Sys.time()
sessionInfo()
```

